name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job_build_release_plugin:
    name: Build plugin
    strategy:
      matrix:
        include:
          - sdk: "$NANOS_SDK"
            name: "nanos"
          - sdk: "$NANOX_SDK"
            name: "nanox"
          - sdk: "$NANOSP_SDK"
            name: "nanosp"

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Clone SDK
        uses: actions/checkout@v3
        with:
          repository: LedgerHQ/ethereum-plugin-sdk
          path: ethereum-plugin-sdk
          ref: ${{ github.base_ref || github.ref_name }}

      - name: Build plugin
        run: |
          make clean
          make BOLOS_SDK=${{ matrix.sdk }} -j

  job_build_debug_plugin:
    name: Build debug plugin
    strategy:
      matrix:
        include:
          - sdk: "$NANOS_SDK"
            name: "nanos"
          - sdk: "$NANOX_SDK"
            name: "nanox"
          - sdk: "$NANOSP_SDK"
            name: "nanosp"

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Clone SDK
        uses: actions/checkout@v3
        with:
          repository: LedgerHQ/ethereum-plugin-sdk
          path: ethereum-plugin-sdk
          ref: ${{ github.base_ref || github.ref_name }}

      - name: Build plugin
        run: |
          make DEBUG=1 BOLOS_SDK=${{ matrix.sdk }} -j

      - name: Move binary to test directory
        run: |
          mkdir -p ./tests/elfs/
          mv bin/app.elf ./tests/elfs/plugin_${{ matrix.name }}.elf

      - name: Upload plugin binary
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: tests/elfs/plugin_${{ matrix.name }}.elf

  job_build_debug_app:
    name: Build debug app
    strategy:
      matrix:
        include:
          - sdk: "$NANOS_SDK"
            name: "nanos"
          - sdk: "$NANOX_SDK"
            name: "nanox"
          - sdk: "$NANOSP_SDK"
            name: "nanosp"

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:latest

    steps:
      - name: Checkout app-ethereum
        uses: actions/checkout@v3
        with:
          repository: LedgerHQ/app-ethereum
          ref: ${{ github.base_ref || github.ref_name }}
          submodules: recursive

      - name: Build ethereum
        run: |
          make DEBUG=1 BYPASS_SIGNATURES=1 BOLOS_SDK=${{ matrix.sdk }} -j

      - name: Move binary to test directory
        run: |
          mkdir -p ./tests/elfs/
          mv bin/app.elf ./tests/elfs/ethereum_${{ matrix.name }}.elf

      - name: Upload plugin binary
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: tests/elfs/ethereum_${{ matrix.name }}.elf

  jobs-e2e-tests:
    name: E2E Tests
    needs: [job_build_debug_plugin, job_build_debug_app]
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          id
          echo $HOME
          echo $DISPLAY

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download built binaries
        uses: actions/download-artifact@v3
        with:
          name: binaries
          path: tests/elfs/

      - name: Check downloaded binaries
        run: ls -lh ./tests/elfs

      - name: Install system dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libusb-1.0.0 libudev-dev

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"

      - name: Install yarn
        run: |
          npm install -g yarn

      - name: Build/Install build js deps
        run: |
          cd tests && yarn install

      - name: Run zemu tests
        run: |
          cd tests && yarn test
